# Generated by Django 4.1.3 on 2023-03-01 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='День')),
                ('month', models.CharField(blank=True, choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=20, verbose_name='Месяц')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование праздника')),
                ('photo', models.ImageField(blank=True, upload_to='holidays/', verbose_name='Изображение')),
                ('about', models.TextField(max_length=1000, verbose_name='Описание праздника')),
                ('isactive', models.BooleanField(default=False, verbose_name='отображать')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Runningrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='День')),
                ('month', models.CharField(blank=True, choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=20, verbose_name='Месяц')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование праздника')),
                ('photo', models.ImageField(blank=True, upload_to='holidays/', verbose_name='Изображение')),
                ('about', models.TextField(max_length=1000, verbose_name='Описание праздника')),
                ('isactive', models.BooleanField(default=False, verbose_name='отображать')),
            ],
            options={
                'verbose_name': 'Праздник',
                'verbose_name_plural': 'Праздники',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Название слайда')),
                ('image', models.ImageField(blank=True, upload_to='slides/', verbose_name='изображение слайда')),
                ('isactive', models.BooleanField(default=True, verbose_name='отображать')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
                'ordering': ['title'],
            },
        ),
    ]
