# Generated by Django 4.1.3 on 2023-03-01 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='runningrow',
            options={'ordering': ['name'], 'verbose_name': 'Бегущая строка', 'verbose_name_plural': 'Бегущие строки'},
        ),
        migrations.RemoveField(
            model_name='runningrow',
            name='photo',
        ),
        migrations.AddField(
            model_name='holidays',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2050)], verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='holidays',
            name='month',
            field=models.CharField(choices=[('1', 'Январь'), ('2', 'Февраль'), ('3', 'Март'), ('4', 'Апрель'), ('5', 'Май'), ('6', 'Июнь'), ('7', 'Июль'), ('8', 'Август'), ('9', 'Сентябрь'), ('10', 'Октябрь'), ('11', 'Ноябрь'), ('12', 'Декабрь')], max_length=20, verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='runningrow',
            name='about',
            field=models.TextField(max_length=1000, verbose_name='Текст строки'),
        ),
        migrations.AlterField(
            model_name='runningrow',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Наименование события'),
        ),
    ]
